---
title: "Bike Crazy"
author: "David Jackson"
date: "7/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
```

## R Markdown

```{r}
station_count <-tibble::tribble(
                            ~start_station_name,   ~Cnt,
                   "Ashland Ave & Augusta Blvd",  4492L,
                              "Millennium Park", 21730L,
                      "Lake Park Ave & 56th St",  4461L,
                          "Ellis Ave & 58th St",  3273L,
       "HUBBARD ST BIKE CHECKING (LBS-WH-TEST)",   405L,
                           "Clark St & Lake St", 10412L,
                      "Lincoln Ave & Roscoe St",  7350L,
                    "Larrabee St & Division St",  7701L,
                     "South Shore Dr & 74th St",   879L,
                   "Franklin St & Jackson Blvd",  8779L,
                   "Sheridan Rd & Columbia Ave",  3006L,
                        "Clark St & Jarvis Ave",   935L,
                      "Sedgwick St & North Ave",  9443L,
                         "Halsted St & 47th Pl",   497L,
                  "Spaulding Ave & Division St",  1853L,
                         "Wabash Ave & 16th St",  6796L,
                    "Washtenaw Ave & Ogden Ave",   757L,
                         "Clark St & North Ave", 10372L,
                    "Clinton St & Roosevelt Rd",  5132L,
                        "Michigan Ave & Oak St", 19626L,
                           "Rush St & Cedar St", 13230L,
                                 "Bradley Park",    31L,
                    "Claremont Ave & Hirsch St",  1515L,
                       "Damen Ave & Leland Ave",  3823L,
                      "State St & Van Buren St",  4736L,
                       "Western Ave & Lunt Ave",  1636L,
                    "Halsted St & Clybourn Ave", 10505L,
               "Valli Produce - Evanston Plaza",   987L,
                 "Sheffield Ave & Waveland Ave", 12200L,
                               "Burnham Harbor", 11859L,
         "Orleans St & Chestnut St (NEXT Apts)",  6674L,
                       "Ridge Blvd & Howard St",   483L,
                      "Laramie Ave & Kinzie St",    85L,
                    "Wood St & Chicago Ave (*)",    64L,
                        "Dayton St & North Ave",  6632L,
                              "Kosciuszko Park",  1961L,
                "Major Taylor Trail & 115th St",    54L,
                      "Wolcott Ave & Fargo Ave",   358L,
                 "Sheridan Rd & Irving Park Rd",  8758L,
                    "Cherry Ave & Blackhawk St",   613L,
                       "Clark St & Randolph St",  8078L,
                  "Cottage Grove Ave & 43rd St",  1175L,
                     "Hoyne Ave & Balmoral Ave",   909L,
                        "Austin Blvd & Lake St",   484L,
                      "Aberdeen St & Monroe St",  5129L,
                    "Leavitt St & Armitage Ave",  3805L,
                  "Lincoln Ave & Fullerton Ave", 14375L,
                      "Marquette Ave & 89th St",    46L,
                      "Lake Park Ave & 47th St",  2292L,
                       "Michigan Ave & 71st St",   102L,
                      "Carpenter St & Huron St",  6436L,
                            "Wood St & 35th St",   676L,
                  "Western Ave & Winnebago Ave",  5796L,
                       "Oakley Ave & Touhy Ave",   568L,
                       "Jeffery Blvd & 67th St",   861L,
                      "Eberhart Ave & 131st St",    20L,
                      "Torrence Ave & 126th Pl",    12L,
                          "Ellis Ave & 60th St",  4628L,
                     "Commercial Ave & 83rd St",   241L,
                   "LaSalle St & Washington St",  6104L,
                   "Dearborn St & Van Buren St",  3766L,
                    "Kimball Ave & Belmont Ave",  1554L,
                          "Dodge Ave & Main St",     3L,
                       "Michigan Ave & 14th St",  9550L,
                   "Greenview Ave & Jarvis Ave",  2067L,
                       "Indiana Ave & 103rd St",    88L,
                             "May St & 69th St",    51L,
              "Pine Grove Ave & Irving Park Rd", 11834L,
                    "Chicago Ave & Dempster St",  2001L,
                          "Hale Ave & 107th St",    20L,
                       "Kedzie Ave & Palmer Ct",  3717L,
                 "Ravenswood Ave & Berteau Ave",  2181L,
                 "Fairfield Ave & Roosevelt Rd",   445L,
                    "Western Ave & Division St",  3654L,
                 "Cornell Ave & Hyde Park Blvd",  6450L,
                        "Ashland Ave & Lake St",  2309L,
                          "Buckingham Fountain", 11611L,
                    "Western Ave & Fillmore St",  2330L,
                       "Jeffery Blvd & 76th St",   259L,
                      "Greenwood Ave & 91st St",    50L,
                    "Blue Island Ave & 18th St",  3525L,
                         "Wabash Ave & 83rd St",   136L,
                   "Burling St & Diversey Pkwy",  2329L,
               "Lake Shore Dr & Wellington Ave", 19770L,
                     "Loomis St & Lexington St",  9230L,
                      "Western Ave & Monroe St",  1730L,
                  "South Chicago Ave & 83rd St",    83L,
                   "Kildare Ave & Montrose Ave",   624L,
                     "Kedzie Ave & Chicago Ave",  1025L,
                "Christiana Ave & Lawrence Ave",  1234L,
                       "Seeley Ave & Roscoe St",  3602L,
                    "Stewart Ave & 63rd St (*)",     1L,
                    "Sedgwick St & Webster Ave",  9073L,
                          "Troy St & North Ave",  3024L,
                      "Wentworth Ave & 33rd St",   748L,
                      "Wentworth Ave & 63rd St",   157L,
                     "Cicero Ave & Flournoy St",    59L,
                 "Humboldt Blvd & Armitage Ave",  4147L,
                    "Elston Ave & Wabansia Ave",  2210L,
                     "Clark St & 9th St (AMLI)",  4346L,
                  "Field Blvd & South Water St",  7851L,
                       "Woodlawn Ave & 55th St",  3242L,
                      "Eggleston Ave & 69th St",   103L,
                        "Vernon Ave & 107th St",    67L,
                   "Pulaski Rd & Congress Pkwy",   151L,
                       "Western Ave & 104th St",     1L,
                      "Larrabee St & North Ave",  4377L,
                     "Sheridan Rd & Loyola Ave",  4296L,
                  "Lincoln Ave & Diversey Pkwy",  8706L,
                       "Woodlawn Ave & 75th St",    82L,
                       "Drake Ave & Addison St",   460L,
                    "Damen Ave & Charleston St",  3706L,
                       "Phillips Ave & 79th St",   292L,
                         "Kedzie Ave & 24th St",   253L,
                  "Sheridan Rd & Greenleaf Ave",  2660L,
                     "Wells St & Evergreen Ave", 17097L,
                     "Wilton Ave & Belmont Ave", 15878L,
                           "State St & 33rd St",  4188L,
                 "Campbell Ave & Fullerton Ave",  3036L,
                         "Pulaski Rd & Lake St",   191L,
                  "Eggleston Ave & 69th St (*)",     3L,
                   "Ashland Ave & Blackhawk St",  7440L,
                         "Ogden Ave & Race Ave",  6458L,
                      "Talman Ave & Addison St",  1827L,
                         "Clinton St & 18th St",  1951L,
                       "Paulina St & Howard St",  1237L,
                         "Federal St & Polk St", 11512L,
                    "Paulina St & Montrose Ave",  2408L,
                   "Central Park Ave & 24th St",   179L,
                    "Sedgwick St & Schiller St",  3224L,
                    "Commercial Ave & 130th St",    22L,
                   "Racine Ave & Fullerton Ave",  7106L,
                          "Damen Ave & 59th St",   130L,
                              "McCormick Place",  1632L,
                   "Racine Ave & Garfield Blvd",   255L,
                     "Leavitt St & Chicago Ave",  3409L,
              "Ravenswood Ave & Irving Park Rd",  3769L,
                  "Central Park Blvd & 5th Ave",   230L,
                     "Marshfield Ave & 44th St",   150L,
                        "Indiana Ave & 31st St",  2553L,
                    "Conservatory Dr & Lake St",   656L,
                   "California Ave & Cortez St",  3447L,
                     "Dorchester Ave & 63rd St",   883L,
                      "Princeton Ave & 47th St",   318L,
                      "Michigan Ave & 114th St",    21L,
                            "Ada St & 113th St",    20L,
                         "Rhodes Ave & 71st St",    57L,
                   "Larrabee St & Armitage Ave",  7045L,
                      "Western Ave & Walton St",  5066L,
                         "Wood St & Hubbard St",  2267L,
                     "Glenwood Ave & Morse Ave",  3344L,
                        "Halsted St & 111th St",    56L,
                         "Vernon Ave & 75th St",   193L,
                "Lakeview Ave & Fullerton Pkwy", 17290L,
                   "Ashland Ave & McDowell Ave",   202L,
                     "Ashland Ave & Archer Ave",   613L,
                   "Stony Island Ave & 67th St",   574L,
                        "Calumet Ave & 71st St",   161L,
                           "State St & 29th St",   664L,
                 "Damen Ave & Walnut (Lake) St",  1011L,
                      "Broadway & Waveland Ave", 13608L,
                 "Southport Ave & Clybourn Ave",  4278L,
                        "Evanston Civic Center",   916L,
                      "Orleans St & Hubbard St",  4702L,
                  "Cottage Grove Ave & 63rd St",   503L,
             "W Armitage Ave & N Sheffield Ave",   139L,
                          "Damen Ave & 51st St",    82L,
                   "Indiana Ave & Roosevelt Rd", 21544L,
                   "Damen Ave & Wellington Ave",  3451L,
              "Central Park Ave & Elbridge Ave",  1557L,
                       "Elizabeth St & 92nd St",   133L,
                       "Clark St & Drummond Pl", 15449L,
                  "California Ave & Altgeld St",  3180L,
      "Wolcott (Ravenswood) Ave & Montrose Ave",  3742L,
                    "Eastlake Ter & Rogers Ave",  2473L,
                           "State St & 76th St",    71L,
                       "State St & Pershing Rd",   405L,
                      "Logan Blvd & Elston Ave",  4179L,
                    "Ogden Ave & Congress Pkwy",  1361L,
                    "Michigan Ave & Pearson St",  9235L,
                          "Avenue O & 118th St",    17L,
                     "Vincennes Ave & 104th St",    13L,
                       "Western Ave & 111th St",    12L,
                       "Clark St & Elmdale Ave",  2593L,
  "Burling St (Halsted) & Diversey Pkwy (Temp)",  7126L,
               "Southport Ave & Irving Park Rd",  4579L,
                  "Cottage Grove Ave & 51st St",  1542L,
                 "Cottage Grove Ave & 111th Pl",    57L,
                       "Leavitt St & North Ave",  4103L,
                         "Halsted St & 73rd St",    41L,
                          "Evans Ave & 75th St",   131L,
                   "Clybourn Ave & Division St",  4639L,
                                   "Walsh Park",  3512L,
                      "Clark St & Armitage Ave", 21108L,
                     "Broadway & Thorndale Ave",  4891L,
                         "Halsted St & 35th St",  1143L,
                             "Central St Metra",  1185L,
                        "LaSalle Dr & Huron St",  8586L,
                          "Ellis Ave & 55th St",  3584L,
                       "Marine Dr & Ainslie St",  8432L,
               "Sheffield Ave & Wellington Ave", 12386L,
                    "Lake Shore Dr & Monroe St", 26294L,
                  "Sheffield Ave & Webster Ave", 10760L,
                   "Seeley Ave & Garfield Blvd",   117L,
                 "Racine Ave & Washington Blvd",  1877L,
                   "Stony Island Ave & 90th St",    37L,
                   "Lake Shore Dr & North Blvd", 24980L,
                      "Ashland Ave & Grand Ave",  3521L,
                  "Pulaski Rd & Eddy St (Temp)",   659L,
                "Major Taylor Trail & 124th St",    18L,
                       "Wabash Ave & Wacker Pl", 10563L,
                      "Streeter Dr & Grand Ave", 32446L,
                     "California Ave & Lake St",   585L,
                                "63rd St Beach",  2343L,
                      "Lake Shore Dr & Ohio St", 12154L,
                          "Perry Ave & 69th St",   157L,
               "Throop (Loomis) St & Taylor St",  3240L,
                            "900 W Harrison St",  3304L,
                           "State St & 79th St",   254L,
                         "Broadway & Argyle St",  6027L,
                    "Lincoln Ave & Belmont Ave",  6725L,
                     "Laflin St & Cullerton St",  1817L,
                  "Western Ave & Congress Pkwy",  2207L,
                     "Marshfield Ave & 59th St",    40L,
                      "Eggleston Ave & 92nd St",    80L,
                        "Ashland Ave & 13th St",  1933L,
                        "Ashland Ave & 74th St",    24L,
                 "Keystone Ave & Fullerton Ave",   880L,
                      "Elmwood Ave & Austin St",   659L,
                         "Harper Ave & 59th St",  1821L,
                  "Lake Shore Dr & Belmont Ave", 17140L,
                             "Warren Park East",  1117L,
                        "LaSalle St & Adams St",  2726L,
                        "Shields Ave & 43rd St",    36L,
                         "Racine Ave & 15th St",  1318L,
                        "Halsted St & 104th St",    32L,
                   "Wilton Ave & Diversey Pkwy", 10503L,
                        "Michigan Ave & 8th St", 12127L,
                     "Laramie Ave & Madison St",   229L,
                         "Albany Ave & 26th St",   328L,
                       "Clark St & Chicago Ave", 10328L,
                "Albany Ave & Bloomingdale Ave",  2496L,
                        "Stewart Ave & 83rd St",    62L,
                     "Racine Ave & Belmont Ave",  8399L,
                            "Malcolm X College",   750L,
                     "California Ave & 26th St",   152L,
                        "Damen Ave & Grand Ave",  2992L,
                  "Sawyer Ave & Irving Park Rd",  1146L,
                        "Millard Ave & 26th St",   384L,
                     "Leavitt St & Division St",  1775L,
                        "Shields Ave & 31st St",  1689L,
                   "Lincoln Ave & Waveland Ave",  3957L,
                   "Stony Island Ave & 71st St",   405L,
                    "Clark St & Wrightwood Ave", 15129L,
                        "State St & Pearson St",  7823L,
                           "State St & 19th St",  2416L,
                          "MLK Jr Dr & 29th St",  6068L,
                     "Clark St & Schreiber Ave",  2115L,
                        "Emerald Ave & 28th St",  1755L,
                          "Morgan St & Lake St",  9701L,
                    "Halsted St & Roosevelt Rd",  2297L,
                         "Halsted St & 69th St",    86L,
                        "Ashland Ave & 66th St",   112L,
                            "Clark St & Elm St", 27728L,
                    "Franklin St & Illinois St",  9449L,
                    "California Ave & Byron St",  2027L,
                 "California Ave & Fletcher St",  2133L,
                    "Michigan Ave & Madison St",  6747L,
                          "Hoyne Ave & 47th St",   213L,
                         "Cicero Ave & Lake St",   119L,
                  "Cottage Grove Ave & 71st St",    84L,
                          "Clark St & Grace St",  9475L,
                       "Sedgwick St & Huron St",  7853L,
                         "Broadway & Ridge Ave",  5538L,
                               "Shedd Aquarium", 12132L,
                     "Loomis St & Jackson Blvd",  3686L,
                      "Dearborn St & Monroe St", 10509L,
                     "Damen Ave & Clybourn Ave",  3319L,
                        "Central Ave & Lake St",   204L,
                          "Morgan St & Polk St",  5235L,
                        "Broadway & Berwyn Ave",  6409L,
                      "Leavitt St & Addison St",  1562L,
                           "Shore Dr & 55th St", 10313L,
                     "Western Ave & Leland Ave",  4211L,
                     "Delano Ct & Roosevelt Rd",  4403L,
                    "Latrobe Ave & Chicago Ave",   135L,
                   "Clarendon Ave & Junior Ter",  9065L,
                          "MLK Jr Dr & 47th St",  1045L,
                        "Ashland Ave & 73rd St",     9L,
                            "Adler Planetarium", 11540L,
                          "Throop St & 52nd St",    87L,
             "Racine Ave & Washington Blvd (*)",    29L,
                   "Kedzie Ave & Milwaukee Ave",  8344L,
                       "Loomis St & Archer Ave",   992L,
                    "Ashland Ave & Pershing Rd",   259L,
              "Lakefront Trail & Bryn Mawr Ave", 14992L,
                      "Hermitage Ave & Polk St",  3290L,
                  "Keystone Ave & Montrose Ave",   839L,
                        "Clark St & Leland Ave",  6532L,
                         "Halsted St & 59th St",    89L,
                         "Clark St & Touhy Ave",   706L,
                        "Calumet Ave & 35th St",  1347L,
                 "St. Louis Ave & Balmoral Ave",   853L,
                      "Baltimore Ave & 87th St",    97L,
                       "WATSON TESTING - DIVVY",  2958L,
                               "Smith Park (*)",    36L,
                    "Sheffield Ave & Willow St",  8763L,
                   "Kedzie Ave & Bryn Mawr Ave",   998L,
                  "Cottage Grove Ave & 78th St",   236L,
                      "Damen Ave & Chicago Ave",  7314L,
                "Greenview Ave & Diversey Pkwy",  3774L,
                         "Halsted St & 37th St",   611L,
                               "DuSable Museum",   741L,
                     "Damen Ave & Cullerton St",  2296L,
                          "Clark St & Lunt Ave",  1359L,
                  "Winchester Ave & Elston Ave",  2378L,
                 "Ewing Ave & Burnham Greenway",    25L,
                     "Campbell Ave & North Ave",  3967L,
                          "Canal St & Adams St",  6591L,
                      "Lake Park Ave & 35th St",  3701L,
                "Ravenswood Ave & Lawrence Ave",  6962L,
                           "Wells St & 19th St",  1649L,
                         "Racine Ave & 18th St",  3608L,
                       "Damen Ave & Coulter St",   698L,
                        "Calumet Ave & 21st St",  2185L,
                       "Canal St & Harrison St",  1493L,
                      "Lincoln Ave & Winona St",  1949L,
                       "Cicero Ave & Quincy St",   189L,
                        "Prospect Sq & 91st St",   178L,
                         "Racine Ave & 61st St",    29L,
                 "Leavitt St & Belmont Ave (*)",    55L,
                     "Jefferson St & Monroe St",  5868L,
                      "Wood St & Milwaukee Ave",  9787L,
                           "Daley Center Plaza", 10668L,
                          "Avenue O & 134th St",    34L,
                        "Wells St & Hubbard St", 13562L,
                 "Maplewood Ave & Peterson Ave",   642L,
                  "Racine Ave & Wrightwood Ave",  4648L,
                  "Halsted St & Wrightwood Ave", 10727L,
                 "Sheffield Ave & Kingsbury St",  8748L,
                       "Elizabeth St & 47th St",    95L,
                         "Halsted St & 63rd St",   265L,
                        "Shields Ave & 28th Pl",   885L,
                      "Knox Ave & Montrose Ave",   468L,
          "Mies van der Rohe Way & Chicago Ave", 11693L,
                    "Chicago Ave & Sheridan Rd",  2404L,
                          "State St & 123rd St",    27L,
                        "Wabash Ave & Adams St",  6419L,
                  "Lincolnwood Dr & Central St",   600L,
                          "MLK Jr Dr & 83rd St",   120L,
                  "Dearborn Pkwy & Delaware Pl", 16769L,
                      "Halsted St & Archer Ave",  1015L,
                      "Ogden Ave & Chicago Ave",  6562L,
                    "Ashland Ave & Chicago Ave",  5589L,
                "Lake Shore Dr & Diversey Pkwy", 16823L,
                    "Central Ave & Chicago Ave",   395L,
                    "Cannon Dr & Fullerton Ave",  7055L,
                       "Michigan Ave & Lake St", 17183L,
               "Sheffield Ave & Wrightwood Ave", 10844L,
                      "Sheridan Rd & Buena Ave",  6475L,
               "Wentworth Ave & 24th St (Temp)",  1225L,
                        "Dauphin Ave & 87th St",    47L,
                      "Damen Ave & Division St",  6140L,
                         "Kedzie Ave & 21st St",   313L,
                              "Montrose Harbor", 13657L,
                   "Richmond St & Diversey Ave",  1709L,
               "Ashland Ave & Belle Plaine Ave",  2410L,
                   "Francisco Ave & Foster Ave",  1972L,
                        "Broadway & Wilson Ave",  6655L,
                      "Lake Park Ave & 53rd St",  4272L,
                   "Stony Island Ave & 75th St",   330L,
                         "State St & Kinzie St", 12155L,
                   "Racine Ave & Congress Pkwy",  2214L,
                          "Theater on the Lake", 27543L,
          "Mies van der Rohe Way & Chestnut St", 13020L,
                         "Larrabee St & Oak St",  4406L,
                        "Canal St & Madison St",  4308L,
                     "Bosworth Ave & Howard St",   474L,
                          "Wabash Ave & 9th St", 12790L,
                       "Jeffery Blvd & 71st St",   679L,
                     "Peoria St & Jackson Blvd",  8529L,
                   "Clarendon Ave & Gordon Ter",  8881L,
                 "Spaulding Ave & Armitage Ave",  2238L,
                    "Clark St & Ida B Wells Dr",  3142L,
                          "2112 W Peterson Ave",   789L,
                         "New St & Illinois St",  1269L,
                "Western Ave & Fillmore St (*)",    85L,
                        "Kimbark Ave & 53rd St",  6754L,
               "California Ave & Milwaukee Ave",  6994L,
                     "Racine Ave & Randolph St",  2639L,
                         "Troy St & Elston Ave",  1692L,
                     "Noble St & Milwaukee Ave",  6475L,
                    "Ashland Ave & Division St", 14176L,
                "Kilbourn Ave & Irving Park Rd",   490L,
                        "May St & Cullerton St",  1616L,
                     "LaSalle St & Illinois St", 12462L,
                 "Central Park Ave & Ogden Ave",   437L,
                       "Ridge Blvd & Touhy Ave",   478L,
                   "Stony Island Ave & 64th St",   439L,
                        "N Clark St & W Elm St",     1L,
                 "Milwaukee Ave & Wabansia Ave",  8791L,
           "California Ave & Francis Pl (Temp)",  3071L,
                      "Kenton Ave & Madison St",   100L,
                       "State St & Harrison St",  5601L,
                     "Kedzie Ave & Harrison St",   187L,
                      "Clark St & Winnemac Ave",  6410L,
                  "Prairie Ave & Garfield Blvd",   477L,
                    "Clinton St & Jackson Blvd",  4056L,
                           "State St & 54th St",   190L,
               "Southport Ave & Wrightwood Ave",  6245L,
                   "Larrabee St & Menomonee St",  3783L,
                         "Morgan Ave & 14th Pl",  2631L,
                         "Wabash Ave & 87th St",   230L,
                         "Summit Ave & 86th St",    65L,
              "Blackstone Ave & Hyde Park Blvd",  4191L,
                         "Halsted St & 18th St",  2095L,
                      "Stave St & Armitage Ave",  3010L,
                       "Broadway & Belmont Ave", 11617L,
                    "Drake Ave & Fullerton Ave",  2285L,
                         "Canal St & Taylor St",  3246L,
                   "Clarendon Ave & Leland Ave",  5518L,
                         "Halsted St & 78th St",    54L,
                     "Leavitt St & Belmont Ave",  1830L,
                       "Clinton St & Tilden St",  1957L,
                       "Damen Ave & Madison St",  1398L,
                      "Greenwood Ave & 97th St",   112L,
                  "S Michigan Ave & E 118th St",     1L,
                        "Wolcott Ave & Polk St",  6194L,
                "Financial Pl & Ida B Wells Dr",  3996L,
                      "University Library (NU)",  1825L,
                 "Washtenaw Ave & Lawrence Ave",  2533L,
                      "Damen Ave & Pershing Rd",   618L,
                   "W Oakdale Ave & N Broadway",   482L,
                        "Ashland Ave & 50th St",   121L,
                       "Clark St & Schiller St", 15981L,
                  "Milwaukee Ave & Rockwell St",  3192L,
                     "Dorchester Ave & 49th St",  1077L,
                         "Halsted St & Polk St",  3867L,
              "Monticello Ave & Irving Park Rd",  1104L,
                    "Milwaukee Ave & Grand Ave", 10916L,
                     "Kingsbury St & Kinzie St", 16813L,
                       "Damen Ave & Pierce Ave", 12719L,
                  "Chicago Ave & Washington St",  3022L,
                 "Archer (Damen) Ave & 37th St",   594L,
                           "State St & 95th St",   127L,
                        "Houston Ave & 92nd St",    86L,
                "Franklin St & Adams St (Temp)",  3582L,
                    "Kedzie Ave & Roosevelt Rd",   262L,
                      "Normal Ave & Archer Ave",   975L,
                        "Calumet Ave & 51st St",   839L,
                  "Lincoln Ave & Sunnyside Ave",  3902L,
                          "Morgan St & 18th St",  2757L,
                 "Stetson Ave & South Water St",  7278L,
                           "Wells St & Polk St",  7775L,
                "St. Louis Ave & Fullerton Ave",   397L,
                       "Halsted St & Roscoe St", 14423L,
                      "Bernard St & Elston Ave",   581L,
                 "Marshfield Ave & Cortland St",  5313L,
                       "Western Blvd & 48th Pl",   292L,
                         "Clinton St & Polk St",   623L,
                         "Halsted St & 56th St",    84L,
                    "Desplaines St & Kinzie St", 17495L,
                        "Dodge Ave & Church St",   748L,
                       "Clark St & Lincoln Ave", 20242L,
                 "Lakefront Trail & Wilson Ave",  7125L,
                        "Wells St & Concord Ln", 21760L,
                      "Greenwood Ave & 79th St",   195L,
                         "Halsted St & 21st St",   862L,
                       "Carpenter St & 63rd St",    23L,
                      "Hegewisch Metra Station",     5L,
                     "Drake Ave & Montrose Ave",   891L,
                      "Franklin St & Monroe St",  7761L,
                        "Indiana Ave & 26th St",  3317L,
                       "Broadway & Sheridan Rd",  8637L,
                    "Clark St & Wellington Ave", 13884L,
                   "Clifton Ave & Armitage Ave",  6864L,
                                   "Smith Park",  1057L,
                  "Western Ave & Granville Ave",  1175L,
                  "Desplaines St & Randolph St",  7027L,
                     "South Shore Dr & 71st St",  2150L,
                        "Western Ave & 21st St",  1232L,
                       "Oglesby Ave & 100th St",    63L,
                     "Austin Blvd & Madison St",   387L,
                  "Southport Ave & Belmont Ave",  6517L,
                      "Central St & Girard Ave",  1255L,
                  "Cottage Grove Ave & 83rd St",   245L,
                    "Wacker Dr & Washington St",  4195L,
                          "Wells St & Huron St", 18983L,
                    "Lincoln Park Conservatory", 10511L,
                        "Wood St & Chicago Ave",  2837L,
                       "Kostner Ave & Adams St",   215L,
                       "St. Clair St & Erie St", 17954L,
                       "State St & Randolph St", 11350L,
                      "Morgan St & Pershing Rd",   125L,
                    "Albany Ave & Montrose Ave",  1659L,
                    "Artesian Ave & Hubbard St",  1857L,
                         "Yates Blvd & 75th St",   290L,
                   "Wood St & Taylor St (Temp)",  1275L,
               "Southport Ave & Wellington Ave",  7748L,
                         "Broadway & Barry Ave", 21023L,
                       "Walden Pkwy & 100th St",    62L,
                        "Clark St & Newport St",  9954L,
                 "Desplaines St & Jackson Blvd",  8352L,
                       "Ashland Ave & Grace St",  3800L,
                         "Vernon Ave & 79th St",   122L,
                      "Broadway & Cornelia Ave", 16181L,
               "Lincoln Ave & Belle Plaine Ave",  4157L,
                        "Western Ave & 24th St",   727L,
                        "Western Ave & 28th St",   307L,
                      "Leavitt St & Archer Ave",   580L,
                       "Dearborn St & Adams St",  4571L,
                  "Cottage Grove Ave & 47th St",  1263L,
                        "Kostner Ave & Lake St",    49L,
                       "Wabash Ave & Grand Ave", 18609L,
                      "Greenwood Ave & 47th St",  1986L,
                        "Emerald Ave & 31st St",  2817L,
                      "Wentworth Ave & 35th St",   496L,
                "Greenview Ave & Fullerton Ave",  6998L,
                     "Glenwood Ave & Touhy Ave",  1219L,
                       "East End Ave & 87th St",    65L,
                     "California Ave & 23rd Pl",   885L,
                   "Rockwell St & Eastwood Ave",  2057L,
                      "MLK Jr Dr & Pershing Rd",  1880L,
                     "Wentworth Ave & 104th St",    16L,
                   "Larrabee St & Kingsbury St",  7956L,
                     "McClurg Ct & Illinois St", 13712L,
                          "MLK Jr Dr & 63rd St",   280L,
              "Sacramento Blvd & Franklin Blvd",   411L,
                    "Austin Blvd & Chicago Ave",   280L,
                          "Clyde Ave & 87th St",    30L,
                        "Ashland Ave & 78th St",   116L,
                       "Dodge Ave & Mulford St",   738L,
                     "University Ave & 57th St",  5189L,
                    "Damen Ave & Sunnyside Ave",  2507L,
                 "Central Park Ave & North Ave",  1031L,
                     "Ada St & Washington Blvd",  5364L,
                                 "Field Museum",  2798L,
                         "Halsted St & 96th St",    55L,
              "Cityfront Plaza Dr & Pioneer Ct",  9312L,
                   "Fort Dearborn Dr & 31st St",  9258L,
                         "Rush St & Hubbard St",  5810L,
                    "Franklin St & Chicago Ave",  8526L,
                  "Ashland Ave & Garfield Blvd",   152L,
         "Damen Ave & Thomas St (Augusta Blvd)",  5748L,
                "Sangamon St & Washington Blvd",  5117L,
                     "Central Ave & Madison St",   284L,
                         "Halsted St & 51st St",   101L,
                        "Ashland Ave & 69th St",    63L,
                       "Dauphin Ave & 103rd St",    46L,
             "Wentworth Ave & Cermak Rd (Temp)",   321L,
                   "Stony Island Ave & 82nd St",   205L,
                     "Laramie Ave & Gladys Ave",    74L,
                      "Lawndale Ave & 111th St",    10L,
                       "Benson Ave & Church St",  3305L,
                          "Wood St & Taylor St",  3185L,
                                 "Eckhart Park",  6833L,
                     "California Ave & 21st St",   748L,
                       "Michigan Ave & 18th St",  7955L,
                 "Ashland Ave & Wrightwood Ave",  4242L,
                               "Big Marsh Park",    96L,
                 "Leavitt St & Division St (*)",    77L,
                  "Winthrop Ave & Lawrence Ave",  3805L,
                                "Rainbow Beach",   424L,
                         "Kedzie Ave & Lake St",   671L,
                  "Burnham Greenway & 105th St",    37L,
                   "Fairbanks St & Superior St",  5467L,
                 "Woodlawn Ave & Lake Park Ave",  1686L,
                      "Damen Ave & Melrose Ave",  2358L,
                        "Loomis Blvd & 84th St",   114L,
                        "Rush St & Superior St", 11642L,
                    "LaSalle St & Jackson Blvd",  6034L,
                        "Budlong Woods Library",   893L,
                      "Clark St & Columbia Ave",  1284L,
                           "State St & 35th St",  1927L,
                  "Campbell Ave & Montrose Ave",  2239L,
                       "Wood St & Augusta Blvd",  4241L,
                       "Eberhart Ave & 91st St",    99L,
                        "Green St & Madison St", 13233L,
                         "McClurg Ct & Erie St", 12832L,
                          "Morgan St & 31st St",  1721L,
                      "Clinton St & Madison St", 10841L,
                          "Union Ave & Root St",   548L,
                      "Honore St & Division St",  7695L,
                          "Ellis Ave & 83rd St",   136L,
               "Elizabeth (May) St & Fulton St",  3056L,
                   "Sheridan Rd & Montrose Ave", 10334L,
                        "Bennett Ave & 79th St",   114L,
                         "Racine Ave & 35th St",   746L,
                "Pine Grove Ave & Waveland Ave", 15414L,
                  "Sheridan Rd & Noyes St (NU)",  2299L,
                    "Wentworth Ave & Cermak Rd",  4005L,
                      "Paulina Ave & North Ave",  6254L,
                        "Throop St & Taylor St",  1061L,
                  "Michigan Ave & Jackson Blvd",  6619L,
                       "Eberhart Ave & 61st St",   472L,
                     "Ogden Ave & Roosevelt Rd",  1751L,
                 "Halsted St & North Branch St",  1207L,
                         "Racine Ave & 13th St",   846L,
                    "Columbus Dr & Randolph St", 18550L,
                     "Lincoln Ave & Addison St",  2324L,
                      "Homewood Ave & 115th St",     8L,
                       "Green St & Randolph St",  9739L,
                               "Dusable Harbor", 10618L,
                        "Calumet Ave & 18th St",  6242L,
   "Winchester (Ravenswood) Ave & Balmoral Ave",  1059L,
                         "Racine Ave & 65th St",    72L,
                      "Vincennes Ave & 75th St",    71L,
                       "Halsted St & Willow St",  7398L,
                        "Calumet Ave & 33rd St",  2952L,
                      "Damen Ave & Cortland St",  7520L,
                    "Aberdeen St & Randolph St",  4819L,
                    "Larrabee St & Webster Ave", 18297L,
                      "Kedzie Ave & Leland Ave",  1281L,
                "Avondale Ave & Irving Park Rd",   978L,
                         "Wells St & Walton St",  6504L,
                      "Halsted St & Maxwell St",  3894L,
                       "Jeffery Blvd & 91st St",    19L,
                     "Clark St & Bryn Mawr Ave",  4743L,
                    "Wabash Ave & Roosevelt Rd", 17985L,
                  "Oakley Ave & Irving Park Rd",  1750L,
          "Central Park Ave & Bloomingdale Ave",  1848L,
                    "Central Ave & Harrison St",   210L,
                             "Warren Park West",  1197L,
                          "Ellis Ave & 53rd St",  3589L,
                      "Karlov Ave & Madison St",   143L,
                        "Stewart Ave & 63rd St",    76L,
                      "Clark St & Montrose Ave",  4120L,
                 "Kilbourn Ave & Milwaukee Ave",   527L,
                "Sheffield Ave & Fullerton Ave",  7757L,
         "Stony Island Ave & South Chicago Ave",   177L,
                 "Michigan Ave & Washington St", 14599L,
                       "Damen Ave & Foster Ave",  3257L,
                      "Western Ave & Howard St",   591L,
               "South Chicago Ave & Elliot Ave",    31L,
                   "Aberdeen St & Jackson Blvd",  7138L,
                 "Ashland Ave & Wellington Ave",  4135L,
                       "Manor Ave & Leland Ave",  1638L,
                        "Franklin St & Lake St",  8478L,
                   "Sheridan Rd & Lawrence Ave",  4527L,
                          "Orleans St & Elm St",  3212L,
                      "Avers Ave & Belmont Ave",  1413L,
                 "Southport Ave & Waveland Ave", 11422L,
                      "Kedzie Ave & Foster Ave",  1099L,
                        "Prairie Ave & 43rd St",   972L,
                    "Leavitt St & Lawrence Ave",  1954L,
                   "Milwaukee Ave & Cuyler Ave",   803L,
                        "Ritchie Ct & Banks St",  9796L,
                       "Elizabeth St & 59th St",    25L,
                         "Clinton St & Lake St",  8615L,
             "Cottage Grove Ave & Oakwood Blvd",  2270L,
               "Museum of Science and Industry",  3227L,
                        "Dearborn St & Erie St", 20117L,
                  "Cottage Grove Ave & 67th St",   292L,
                     "Broadway & Granville Ave",  7099L,
                         "Canal St & Monroe St",  2562L,
                       "Wabash Ave & Cermak Rd",  1970L,
                "California Ave & Montrose Ave",  3370L,
                       "Exchange Ave & 79th St",   178L,
                       "Phillips Ave & 83rd St",   198L,
                    "Southport Ave & Roscoe St", 12138L,
                         "Paulina St & 18th St",  3319L,
                      "Western Ave & Roscoe St",  2121L,
             "Damen Ave & Walnut (Lake) St (*)",    15L,
                      "Constance Ave & 95th St",    32L,
                      "Torrence Ave & 106th St",    39L,
                             "hubbard_test_lws",     3L,
                        "Cornell Dr & Hayes Dr",   483L,
                         "Rhodes Ave & 32nd St",  2958L,
                "Michigan Ave & Ida B Wells Dr",  4352L,
                            "Wells St & Elm St", 19715L,
                     "Paulina St & Flournoy St",  5628L,
                     "Halsted St & Dickens Ave", 10975L,
                     "Southport Ave & Clark St",  2501L,
                         "Wallace St & 35th St",  1241L,
                 "California Ave & Division St",  3687L,
                          "MLK Jr Dr & 56th St",   407L,
                     "Fairbanks Ct & Grand Ave", 16750L,
                 "Stockton Dr & Wrightwood Ave", 15035L,
                        "Clark St & Berwyn Ave",  7399L,
                     "South Shore Dr & 67th St",  1697L,
                "Princeton Ave & Garfield Blvd",   224L,
                       "Kingsbury St & Erie St", 13398L,
                 "Clinton St & Washington Blvd",  6833L,
                   "California Ave & North Ave",  3462L,
                      "Canal St & Jackson Blvd",  2077L,
                        "Indiana Ave & 40th St",   570L,
                        "Ashland Ave & 63rd St",   109L,
                    "Bissell St & Armitage Ave", 13028L,
                           "May St & Taylor St",  5934L,
          "Orleans St & Merchandise Mart Plaza",  7775L
  )
```

## Plot of Count by Start Station Name 

```{r}
station_count %>% top_n(20) %>%ggplot() + geom_col(aes(x=reorder(start_station_name,Cnt),y=Cnt)) + coord_flip() +
  scale_y_continuous(labels = comma) +
  labs(title = "Count by Start Station",x="Count of Starts",y="Top 20 Start Statoins")
```

### Plot of rides by date

```{r}
rides_day <-tibble::tribble(
         ~Date,   ~Cnt,
  "2020-10-20",  8736L,
  "2020-07-29", 15481L,
  "2020-05-07",  4997L,
  "2020-04-17",  1435L,
  "2020-05-24", 14836L,
  "2020-09-30", 13703L,
  "2020-07-09", 14801L,
  "2020-09-10", 10315L,
  "2020-06-19", 16307L,
  "2020-10-17", 13765L,
  "2020-07-26", 19811L,
  "2020-05-04",  2634L,
  "2020-08-21", 22366L,
  "2020-05-30", 17162L,
  "2020-09-27", 20340L,
  "2020-07-06", 14826L,
  "2020-04-14",  1609L,
  "2020-11-12",  8500L,
  "2020-06-16", 12081L,
  "2020-10-23",  6570L,
  "2020-08-01", 23231L,
  "2020-11-29",  5164L,
  "2020-09-07", 23407L,
  "2020-05-10",  1394L,
  "2020-04-20",  3903L,
  "2020-10-03", 14087L,
  "2020-07-12", 22680L,
  "2020-11-09", 13384L,
  "2020-08-18", 19168L,
  "2020-05-27",  8121L,
  "2020-05-16",  8975L,
  "2020-10-29",  7686L,
  "2020-08-07", 22520L,
  "2020-09-13", 23557L,
  "2020-06-22",  7036L,
  "2020-07-18", 22991L,
  "2020-11-15",  3138L,
  "2020-08-24", 16260L,
  "2020-04-26",  6200L,
  "2020-10-09", 20501L,
  "2020-05-13",  5762L,
  "2020-08-04", 17682L,
  "2020-09-19", 22951L,
  "2020-06-28", 20383L,
  "2020-10-26",  6202L,
  "2020-04-06",  2427L,
  "2020-04-23",  2284L,
  "2020-11-21",  7407L,
  "2020-08-30", 24536L,
  "2020-06-08", 10368L,
  "2020-10-06", 15534L,
  "2020-07-15",  9348L,
  "2020-09-16", 18890L,
  "2020-06-25", 16001L,
  "2020-04-03",  3532L,
  "2020-11-01",  5597L,
  "2020-06-05",  8922L,
  "2020-11-18",  6917L,
  "2020-08-27", 16835L,
  "2020-04-09",  1972L,
  "2020-09-22", 17516L,
  "2020-07-01", 15827L,
  "2020-11-07", 22821L,
  "2020-08-16", 24355L,
  "2020-05-25", 14268L,
  "2020-05-05",  1953L,
  "2020-10-18",  4861L,
  "2020-07-27", 15074L,
  "2020-11-24",  2536L,
  "2020-09-02", 19337L,
  "2020-06-11", 12275L,
  "2020-11-04", 11479L,
  "2020-08-13", 18492L,
  "2020-05-22",  7569L,
  "2020-09-28", 10759L,
  "2020-07-07", 14450L,
  "2020-05-02", 11811L,
  "2020-10-15", 12003L,
  "2020-07-24", 20673L,
  "2020-05-19",  2852L,
  "2020-04-12",  3670L,
  "2020-09-25", 22204L,
  "2020-07-04", 19931L,
  "2020-08-10",  9683L,
  "2020-09-05", 28289L,
  "2020-06-14", 14602L,
  "2020-10-12",  9260L,
  "2020-07-21", 12546L,
  "2020-04-29",   645L,
  "2020-11-27",  5040L,
  "2020-06-03",  6296L,
  "2020-10-01", 10827L,
  "2020-07-10", 16912L,
  "2020-04-18",  5116L,
  "2020-11-16",  6707L,
  "2020-08-25", 17362L,
  "2020-06-20", 14665L,
  "2020-09-11", 14567L,
  "2020-11-13",  7609L,
  "2020-08-22", 28695L,
  "2020-05-31",   193L,
  "2020-04-15",  1419L,
  "2020-08-02", 15338L,
  "2020-11-30",  3716L,
  "2020-09-08",  6665L,
  "2020-06-17", 12827L,
  "2020-05-11",  2871L,
  "2020-10-24", 11788L,
  "2020-08-19", 19501L,
  "2020-05-28",  6785L,
  "2020-10-04", 12382L,
  "2020-07-13", 16628L,
  "2020-11-10",  8548L,
  "2020-04-21",  2627L,
  "2020-05-08",  2793L,
  "2020-04-01",  2294L,
  "2020-09-14", 14912L,
  "2020-06-23", 13692L,
  "2020-10-21",  9770L,
  "2020-07-30", 17838L,
  "2020-09-23", 18079L,
  "2020-10-30",  8843L,
  "2020-08-08", 28594L,
  "2020-04-27",  2595L,
  "2020-10-10", 24034L,
  "2020-07-19", 14582L,
  "2020-09-20", 20706L,
  "2020-06-29",  9395L,
  "2020-10-27",  5813L,
  "2020-08-05", 17803L,
  "2020-05-14",  3036L,
  "2020-04-07",  5185L,
  "2020-04-24",  2284L,
  "2020-10-07", 16868L,
  "2020-07-16", 17263L,
  "2020-11-22",  4668L,
  "2020-08-31", 17150L,
  "2020-06-09",  5608L,
  "2020-11-02",  7666L,
  "2020-08-11", 17695L,
  "2020-05-20",  6348L,
  "2020-09-17", 16809L,
  "2020-06-26",  6228L,
  "2020-04-04",  2288L,
  "2020-07-22", 17332L,
  "2020-11-19",  8687L,
  "2020-08-28", 19677L,
  "2020-06-06", 15239L,
  "2020-04-30",  2567L,
  "2020-10-13", 14944L,
  "2020-05-17",   691L,
  "2020-08-17", 17038L,
  "2020-05-26",  7711L,
  "2020-07-02", 16560L,
  "2020-04-10",  2721L,
  "2020-11-08", 17690L,
  "2020-09-03", 18737L,
  "2020-06-12", 11989L,
  "2020-10-19",  7027L,
  "2020-07-28", 18182L,
  "2020-11-25",  3015L,
  "2020-05-06",  4775L,
  "2020-04-16",  2272L,
  "2020-09-29", 13876L,
  "2020-07-08", 15885L,
  "2020-11-05", 11785L,
  "2020-08-14", 20266L,
  "2020-05-23",  8784L,
  "2020-06-18", 13319L,
  "2020-10-16", 11289L,
  "2020-07-25", 26410L,
  "2020-05-03",  9414L,
  "2020-09-09", 12335L,
  "2020-04-13",  1820L,
  "2020-07-05", 18538L,
  "2020-11-11",  8218L,
  "2020-08-20", 19939L,
  "2020-05-29", 10580L,
  "2020-09-26", 25521L,
  "2020-11-28",  6859L,
  "2020-09-06", 16893L,
  "2020-06-15", 10164L,
  "2020-11-17",  6211L,
  "2020-08-26", 18277L,
  "2020-06-04",  7628L,
  "2020-10-02", 14224L,
  "2020-07-11", 23072L,
  "2020-04-19",  5158L,
  "2020-08-06", 19776L,
  "2020-09-12", 10869L,
  "2020-06-21", 14824L,
  "2020-05-15",  7031L,
  "2020-10-28",  9151L,
  "2020-10-08", 15891L,
  "2020-07-17", 19923L,
  "2020-11-14",  6714L,
  "2020-08-23", 20388L,
  "2020-04-25",  1048L,
  "2020-05-12",  4745L,
  "2020-10-25",  8143L,
  "2020-08-03", 13009L,
  "2020-10-05", 12058L,
  "2020-07-14", 17302L,
  "2020-04-22",  1995L,
  "2020-05-09",  7945L,
  "2020-04-02",  2608L,
  "2020-10-22", 12479L,
  "2020-07-31", 21647L,
  "2020-09-15", 17920L,
  "2020-06-24", 12890L,
  "2020-04-28",  3392L,
  "2020-07-20", 16023L,
  "2020-11-26",  3377L,
  "2020-09-04", 21870L,
  "2020-06-13", 14278L,
  "2020-10-11", 18926L,
  "2020-04-08",  2365L,
  "2020-11-06", 15195L,
  "2020-08-15", 23373L,
  "2020-09-21", 15427L,
  "2020-06-30", 14589L,
  "2020-11-23",  6022L,
  "2020-09-01", 10543L,
  "2020-06-10",  7676L,
  "2020-04-05",  2887L,
  "2020-09-18", 16648L,
  "2020-06-27", 20499L,
  "2020-11-03", 11358L,
  "2020-08-12", 18313L,
  "2020-05-21",  5602L,
  "2020-05-01",  4751L,
  "2020-10-14", 14744L,
  "2020-07-23", 18586L,
  "2020-11-20",  9395L,
  "2020-08-29", 28005L,
  "2020-06-07", 13224L,
  "2020-07-03", 20296L,
  "2020-10-31", 12485L,
  "2020-08-09", 23108L,
  "2020-05-18",  3885L,
  "2020-04-11",  4458L,
  "2020-09-24", 18523L
  )

```

```{r}
rides_day$Date <- as.Date(rides_day$Date)
ggplot(rides_day) + geom_line(aes(x=Date,y=Cnt)) +
  geom_smooth(aes(x=Date,y=Cnt)) +
  scale_y_continuous(labels =  comma) +
  labs(title = "Count of Rides by Date", y="Count of Rides",x="Ride Date")
```

